export const GET_MARKERS_SUCCESS = 'GET_MARKERS_SUCCESS';
export const POST_MARKERS_SUCCESS = 'POST_MARKERS_SUCCESS';
export const UPDATE_MARKERS_SUCCESS = 'UPDATE_MARKERS_SUCCESS';
export const DELETE_MARKERS_SUCCESS = 'DELETE_MARKERS_SUCCESS';
export const SHOW_LOADER = 'SHOW_LOADER';
export const CLOSE_LOADER = 'CLOSE_LOADER';
export const Display_CreateEdit_Modal = 'Display_CreateEdit_Modal';